version = 0.1

[default.global.parameters]
stack_name = "recallindia"
region = "ap-south-1"
profile = "firstcommit"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "EnableSchedules=false DemoMode=0 BedrockEnabled=false"

[default.validate.parameters]
lint = true
