/**
 * The recorded ingest run of the CDSCO NSQ June 2025 PDF: 6 pages, 57 table rows → 55 notices.
 * rows[].bbox and the notice mapping come from the v2 replay bundle
 * (/fixtures/ingest-runs-ingest-20260919084944-ab53-*.json); cells[] are the published row
 * (GET /v1/notices, raw_excerpt of JUN-2025-cdsco_pdf-n). Rows 42 and 54 are continuations merged
 * into 41 and 53. Step durations are the brief's recorded values (27.1 s); the bundle's own
 * wall-clock is 38.5 s (see README). The header joins "Manufact uring", which Textract split.
 * Generated by v3 scratch script gen_fixtures.py; do not hand-edit values.
 */
import type { IngestRun } from "./types";

export const ingestRunJune2025: IngestRun = {
  "run_id": "ingest-20260919084944-ab53",
  "month": "JUN-2025",
  "title": "CDSCO NSQ ALERT FOR THE MONTH OF June 2025",
  "method": "textract",
  "pages": 6,
  "rows_in": 57,
  "notices_out": 55,
  "started_at": "2026-09-19T08:49:45.424Z",
  "pdf_url": "https://cdsco.gov.in/opencms/resources/UploadCDSCOWeb/2018/UploadAlertsFiles/CDSCO%20NSQ%20june25.pdf",
  "file_name": "cdsco-nsq-june-2025.pdf",
  "pdf_kb": null,
  "header": [
    "S.No",
    "Product/Drug Name",
    "Batch No.",
    "Manufacturing Date",
    "Expiry Date",
    "Manufactured By",
    "NSQ Result",
    "Reported by CDSCO Laboratory"
  ],
  "steps": [
    {
      "key": "fetch",
      "label": "Fetch PDF",
      "ms": 1400
    },
    {
      "key": "extract",
      "label": "Extract tables",
      "ms": 22300
    },
    {
      "key": "normalise",
      "label": "Normalise",
      "ms": 2100
    },
    {
      "key": "diff",
      "label": "Diff vs last run",
      "ms": 800
    },
    {
      "key": "publish",
      "label": "Publish",
      "ms": 500
    }
  ],
  "diff": {
    "new": 55,
    "updated": 0,
    "existing": 0,
    "total": 55
  },
  "error": null,
  "rows": [
    {
      "page": 1,
      "row": 1,
      "bbox": {
        "left": 0.0663,
        "top": 0.2841,
        "width": 0.851,
        "height": 0.1175
      },
      "cells": [
        "1.",
        "Dextrose Injection I.P. 5%w/v (D5)",
        "1-3098",
        "01/2025",
        "12/2027",
        "M/s. Tam-Bran Pharmaceuticals Pvt. Ltd., Plot No. 212 & 216, Sector-1, Industrial Area, Pithampur, District-Dhar (M.P.) India- 454775",
        "Assay of Dextrose (Anhydrous)",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-1",
        "notice_id": "JUN-2025-cdsco_pdf-1",
        "product": "Dextrose Injection I.P. 5%w/v (D5)",
        "batch": "1-3098",
        "test": "Assay of Dextrose (Anhydrous)",
        "maker": "Tam-Bran Pharmaceuticals Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 2,
      "bbox": {
        "left": 0.0663,
        "top": 0.4016,
        "width": 0.851,
        "height": 0.0779
      },
      "cells": [
        "2.",
        "Dexamethasone Sodium Phosphate Injection I.P. (Dexacos)",
        "P24L220",
        "12/2024",
        "11/2026",
        "M/s. Paksons pharmaceuticals Private Limited, 36, Milestone, Delhi Rohtak Road, Sankhol, Bahadurgarh-124507, Haryana",
        "Free Dexamethasone, Particulate matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-2",
        "notice_id": "JUN-2025-cdsco_pdf-2",
        "product": "Dexamethasone Sodium Phosphate Injection I.P. (Dexacos)",
        "batch": "P24L220",
        "test": "Free Dexamethasone, Particulate matter and Description",
        "maker": "Paksons pharmaceuticals Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 3,
      "bbox": {
        "left": 0.0663,
        "top": 0.4795,
        "width": 0.851,
        "height": 0.0779
      },
      "cells": [
        "3.",
        "Methylcobalamin Injection",
        "S4H046",
        "08/2024",
        "01/2026",
        "M/s. Arion Healthcare, Vill. Kishanpura, Baddi, Distt. Solan-174101(H.P.)",
        "Assay of Methylcobalamin, Particulate matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-3",
        "notice_id": "JUN-2025-cdsco_pdf-3",
        "product": "Methylcobalamin Injection",
        "batch": "S4H046",
        "test": "Assay of Methylcobalamin, Particulate matter and Description",
        "maker": "Arion Healthcare",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 4,
      "bbox": {
        "left": 0.0663,
        "top": 0.5573,
        "width": 0.851,
        "height": 0.0783
      },
      "cells": [
        "4.",
        "Tranexamic Acid Injection IP 500 mg/5ml",
        "Z24-185",
        "02/2024",
        "01/2026",
        "M/s. Zee Laboratories Ltd., Behind 47, Industrial Area, Paonta Sahib-173025",
        "Related Substances and Assay of Tranexamic Acid",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-4",
        "notice_id": "JUN-2025-cdsco_pdf-4",
        "product": "Tranexamic Acid Injection IP 500 mg/5ml",
        "batch": "Z24-185",
        "test": "Related Substances and Assay of Tranexamic Acid",
        "maker": "Zee Laboratories Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 5,
      "bbox": {
        "left": 0.0663,
        "top": 0.6357,
        "width": 0.851,
        "height": 0.059
      },
      "cells": [
        "5.",
        "Oxytocin Injection I.P. 1ml",
        "AOX-2402",
        "04/2024",
        "03/2026",
        "M/s. Systochem Laboratories Ltd., B-75 Roop Nagar, Indl. Area, Loni-201102(U.P.)",
        "Assay of Oxytocin",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-5",
        "notice_id": "JUN-2025-cdsco_pdf-5",
        "product": "Oxytocin Injection I.P. 1ml",
        "batch": "AOX-2402",
        "test": "Assay of Oxytocin",
        "maker": "Systochem Laboratories Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 6,
      "bbox": {
        "left": 0.0663,
        "top": 0.6947,
        "width": 0.851,
        "height": 0.0977
      },
      "cells": [
        "6.",
        "Calcium Aspartate, Calcium Orotate, Calcitriol Minerals And Vitamin Tablets",
        "EZF-2107",
        "11/2024",
        "04/2027",
        "M/s. Overseas Health Care Pvt. Ltd., 335 Km. Milestone, National Highway No. 1, P.O. Box No. 25, Phillaur - 144410 (Pb.)",
        "Assay of Calcitriol, Zinc, Magnesium Hydroxide and Folic Acid",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-6",
        "notice_id": "JUN-2025-cdsco_pdf-6",
        "product": "Calcium Aspartate, Calcium Orotate, Calcitriol Minerals And Vitamin Tablets",
        "batch": "EZF-2107",
        "test": "Assay of Calcitriol, Zinc, Magnesium Hydroxide and Folic Acid",
        "maker": "Overseas Health Care Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 7,
      "bbox": {
        "left": 0.0663,
        "top": 0.7924,
        "width": 0.851,
        "height": 0.0972
      },
      "cells": [
        "7.",
        "Ascorbic Acid Injection I.P. (Vitson-C)",
        "P25L269",
        "02/2025",
        "01/2027",
        "M/s. Paksons Pharmaceuticals Private Limitated, 36, Milestone, Delhi Rohtak Road, Sankhol, Bahadurgarh- 124507, Haryana",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-7",
        "notice_id": "JUN-2025-cdsco_pdf-7",
        "product": "Ascorbic Acid Injection I.P. (Vitson-C)",
        "batch": "P25L269",
        "test": "Particulate Matter and Description",
        "maker": "Paksons Pharmaceuticals Private Limitated",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 1,
      "row": 8,
      "bbox": {
        "left": 0.0663,
        "top": 0.8896,
        "width": 0.851,
        "height": 0.0584
      },
      "cells": [
        "8.",
        "Adrenaline Injection IP (Aline Injection 1 ml.)",
        "AL-92",
        "02/2025",
        "04/2026",
        "M/s. Aster Medicines Pvt. Ltd., Plot No. E4(Part), Industrial Area Phase II, Hazipur-844101",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-8",
        "notice_id": "JUN-2025-cdsco_pdf-8",
        "product": "Adrenaline Injection IP (Aline Injection 1 ml.)",
        "batch": "AL-92",
        "test": "Particulate Matter and Description",
        "maker": "Aster Medicines Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 9,
      "bbox": {
        "left": 0.0656,
        "top": 0.0594,
        "width": 0.8516,
        "height": 0.0977
      },
      "cells": [
        "9.",
        "Calcium Gluconate Injection I.P. 10 ml.",
        "MV24B36",
        "02/2024",
        "01/2026",
        "M/s. Martin & Brown Bio- Sciences Pvt.Ltd., K.No- 918/419, Malkumajra, Nalagarh Road, Baddi, Dist- Solan, HP-173205",
        "Particulate Matter, Extractable Volume and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-9",
        "notice_id": "JUN-2025-cdsco_pdf-9",
        "product": "Calcium Gluconate Injection I.P. 10 ml.",
        "batch": "MV24B36",
        "test": "Particulate Matter, Extractable Volume and Description",
        "maker": "Martin & Brown Bio- Sciences Pvt.Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 10,
      "bbox": {
        "left": 0.0656,
        "top": 0.1572,
        "width": 0.8516,
        "height": 0.0779
      },
      "cells": [
        "10.",
        "Rabeprazole Sodium (EC) & Domperidone (SR) Capsules (Sesarab-DSR Capsules )",
        "CG23-0372F",
        "09/2023",
        "08/2025",
        "M/s. Athens Life Sciences, Mauza Rampur Jattan, Nahan Road, Kala Amb, Distt. Sirmour, H.P.-173030",
        "Assay of Rabeprazole Sodium",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-10",
        "notice_id": "JUN-2025-cdsco_pdf-10",
        "product": "Rabeprazole Sodium (EC) & Domperidone (SR) Capsules (Sesarab-DSR Capsules )",
        "batch": "CG23-0372F",
        "test": "Assay of Rabeprazole Sodium",
        "maker": "Athens Life Sciences",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 11,
      "bbox": {
        "left": 0.0656,
        "top": 0.235,
        "width": 0.8516,
        "height": 0.0788
      },
      "cells": [
        "11.",
        "Heparin Injection IP 5000 IU/ml (Flagorin)",
        "DP2143",
        "08/2022",
        "06/2025",
        "M/s. Divine Laboratories Pvt. Ltd., Block No. 471, Dabhasa, Tal. Padra, Dist. Vadodara- 391440, India",
        "pH and Assay of Heparin (Anti- factor-Ila activity)",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-11",
        "notice_id": "JUN-2025-cdsco_pdf-11",
        "product": "Heparin Injection IP 5000 IU/ml (Flagorin)",
        "batch": "DP2143",
        "test": "pH and Assay of Heparin (Anti- factor-Ila activity)",
        "maker": "Divine Laboratories Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 12,
      "bbox": {
        "left": 0.0656,
        "top": 0.3138,
        "width": 0.8516,
        "height": 0.0783
      },
      "cells": [
        "12.",
        "Adrenaline Bitartrate Injection I.P. 1 ml (Aderson Inj.)",
        "P25L262",
        "02/2025",
        "07/2026",
        "M/s. Paksons Pharmaceuticals Private Limited, 36, Milestone, Delhi Rohtak Road, Sankhol, Bahadurgarh-124507, Haryana",
        "Particulate Matter, pH and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-12",
        "notice_id": "JUN-2025-cdsco_pdf-12",
        "product": "Adrenaline Bitartrate Injection I.P. 1 ml (Aderson Inj.)",
        "batch": "P25L262",
        "test": "Particulate Matter, pH and Description",
        "maker": "Paksons Pharmaceuticals Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 13,
      "bbox": {
        "left": 0.0656,
        "top": 0.3922,
        "width": 0.8516,
        "height": 0.0585
      },
      "cells": [
        "13.",
        "Methylcobalamin 1500 mcg (Nuroark)",
        "JIN24-041",
        "08/2024",
        "01/2026",
        "M/s. Janya Biocare Pvt. Ltd., Khasra No.-169, Tanshipur, Roorkee (U.K.)",
        "Description and Particulate Matter",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-13",
        "notice_id": "JUN-2025-cdsco_pdf-13",
        "product": "Methylcobalamin 1500 mcg (Nuroark)",
        "batch": "JIN24-041",
        "test": "Description and Particulate Matter",
        "maker": "Janya Biocare Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 14,
      "bbox": {
        "left": 0.0656,
        "top": 0.4507,
        "width": 0.8516,
        "height": 0.0977
      },
      "cells": [
        "14.",
        "Calcium Aspartate, Calcium Orotate, Calcitriol, Minerals and Vitamins Tablets",
        "EZF-2067",
        "10/2024",
        "03/2027",
        "M/s. Overseas Health Care Pvt. Ltd. 335 km, Milestone National Highway No. 1 P.O. Box No. 25, Phillaur-144 410(Pb.)",
        "Assay/ Content of Folic Acid, Zinc and Magnesium Hydroxide",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-14",
        "notice_id": "JUN-2025-cdsco_pdf-14",
        "product": "Calcium Aspartate, Calcium Orotate, Calcitriol, Minerals and Vitamins Tablets",
        "batch": "EZF-2067",
        "test": "Assay/ Content of Folic Acid, Zinc and Magnesium Hydroxide",
        "maker": "Overseas Health Care Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 15,
      "bbox": {
        "left": 0.0656,
        "top": 0.5484,
        "width": 0.8516,
        "height": 0.1166
      },
      "cells": [
        "15.",
        "Fosfomycin Phenyl Ethyl Amine",
        "20240901",
        "12-09-2024",
        "11-09- 2026",
        "M/s. Shayamg Qinjiang Chemical, Add:-No. I Qinjing Chemical Park, Shayang Economic Development Zone, Hubei, China, Postal Code- 448200",
        "Specific Optical Rotation",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-15",
        "notice_id": "JUN-2025-cdsco_pdf-15",
        "product": "Fosfomycin Phenyl Ethyl Amine",
        "batch": "20240901",
        "test": "Specific Optical Rotation",
        "maker": "Shayamg Qinjiang Chemical",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 16,
      "bbox": {
        "left": 0.0656,
        "top": 0.6649,
        "width": 0.8516,
        "height": 0.0972
      },
      "cells": [
        "16.",
        "Gentamicin Injection IP (Gentacos)",
        "P24L199",
        "12/2024",
        "11/2026",
        "M/s. Paksons Pharmaceuticals Private Limited, Delhi Rohtak Road, Ganpati Industrial area, Sankhol, Bahadurgarh- 124507(HR), INDIA",
        "Sterility, Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-16",
        "notice_id": "JUN-2025-cdsco_pdf-16",
        "product": "Gentamicin Injection IP (Gentacos)",
        "batch": "P24L199",
        "test": "Sterility, Particulate Matter and Description",
        "maker": "Paksons Pharmaceuticals Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 17,
      "bbox": {
        "left": 0.0656,
        "top": 0.7622,
        "width": 0.8516,
        "height": 0.0977
      },
      "cells": [
        "17.",
        "Docetaxel Anhydrous IP",
        "DXT2024120 40",
        "12/2024",
        "12/2026",
        "M/s. Sanghai Jinhe Bio- Pharmaceutical Co. Ltd. 508, Maodian Road, Qingpu District, Shanghai-201716, China",
        "Water",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-17",
        "notice_id": "JUN-2025-cdsco_pdf-17",
        "product": "Docetaxel Anhydrous IP",
        "batch": "DXT2024120 40",
        "test": "Water",
        "maker": "Sanghai Jinhe Bio- Pharmaceutical Co. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 2,
      "row": 18,
      "bbox": {
        "left": 0.0656,
        "top": 0.8598,
        "width": 0.8516,
        "height": 0.0775
      },
      "cells": [
        "18.",
        "Ketoconazole & Zinc Pyrithione Shampoo (Ketocross Shampoo)",
        "L25Y2002",
        "03/2025",
        "02/2027",
        "M/s. Om Sai Pharma Pack, Plot No. 38 & 39, Sector- IIE, SIDCUL, Distt. Haridwar, Uttarakhand-249403",
        "Assay of Zinc Pyrithione",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-18",
        "notice_id": "JUN-2025-cdsco_pdf-18",
        "product": "Ketoconazole & Zinc Pyrithione Shampoo (Ketocross Shampoo)",
        "batch": "L25Y2002",
        "test": "Assay of Zinc Pyrithione",
        "maker": "Om Sai Pharma Pack",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 19,
      "bbox": {
        "left": 0.0652,
        "top": 0.0588,
        "width": 0.8512,
        "height": 0.079
      },
      "cells": [
        "19.",
        "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit B 12)",
        "VHI034047",
        "08/2024",
        "07/2026",
        "M/s. Vidit Healthcare, Village Kishanpura, Paonta Sahib, Distt. Sirmour, H.P.-173025",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-19",
        "notice_id": "JUN-2025-cdsco_pdf-19",
        "product": "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit B 12)",
        "batch": "VHI034047",
        "test": "Particulate Matter and Description",
        "maker": "Vidit Healthcare",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 20,
      "bbox": {
        "left": 0.0652,
        "top": 0.1378,
        "width": 0.8512,
        "height": 0.0779
      },
      "cells": [
        "20.",
        "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection)",
        "IEW1433B",
        "07/2024",
        "06/2026",
        "M/s. E.G. Pharmaceuticlas, Vill. Mandhala, Teh. Baddi, Distt. Solan (H.P.)",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-20",
        "notice_id": "JUN-2025-cdsco_pdf-20",
        "product": "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection)",
        "batch": "IEW1433B",
        "test": "Particulate Matter and Description",
        "maker": "E.G. Pharmaceuticlas",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 21,
      "bbox": {
        "left": 0.0652,
        "top": 0.2157,
        "width": 0.8512,
        "height": 0.1364
      },
      "cells": [
        "21.",
        "Rabeprazole Sodium Injection I.P.",
        "MD23H23",
        "08/2023",
        "07/2025",
        "M/s. Martin & Brown Bio- Sciences Pvt.Ltd., K.No- 918/419, Malkumajra, Nalagarh Road, Baddi, Dist- Solan, HP-173205",
        "pH, Clarity of Solution, Particulate Matter, Assay of Rabeprazole Sodium and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-21",
        "notice_id": "JUN-2025-cdsco_pdf-21",
        "product": "Rabeprazole Sodium Injection I.P.",
        "batch": "MD23H23",
        "test": "pH, Clarity of Solution, Particulate Matter, Assay of Rabeprazole Sodium and Description",
        "maker": "Martin & Brown Bio- Sciences Pvt.Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 22,
      "bbox": {
        "left": 0.0652,
        "top": 0.3521,
        "width": 0.8512,
        "height": 0.0401
      },
      "cells": [
        "22.",
        "Clotrimazole Ear Drops",
        "CLT-214A",
        "08/2024",
        "07/2026",
        "M/s. Pushkar Pharma, Kheri, Kala-Amb-173030 (H.P.)",
        "Assay of Clotrimazole",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-22",
        "notice_id": "JUN-2025-cdsco_pdf-22",
        "product": "Clotrimazole Ear Drops",
        "batch": "CLT-214A",
        "test": "Assay of Clotrimazole",
        "maker": "Pushkar Pharma",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 23,
      "bbox": {
        "left": 0.0652,
        "top": 0.3922,
        "width": 0.8512,
        "height": 0.0779
      },
      "cells": [
        "23.",
        "Raberpazole (EC) & Domperidone (SR) Capsules (Rabeton-DSR)",
        "SC-15114",
        "10/2024",
        "09/2027",
        "M/s. Sunvij Drugs Private Limited, 511, GIDC, Waghodia, Baroda-391760, Gujarat",
        "Assay of Rabeprazole Sodium",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-23",
        "notice_id": "JUN-2025-cdsco_pdf-23",
        "product": "Raberpazole (EC) & Domperidone (SR) Capsules (Rabeton-DSR)",
        "batch": "SC-15114",
        "test": "Assay of Rabeprazole Sodium",
        "maker": "Sunvij Drugs Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 24,
      "bbox": {
        "left": 0.0652,
        "top": 0.47,
        "width": 0.8512,
        "height": 0.0585
      },
      "cells": [
        "24.",
        "Telmisartan Tablets IP 40 mg",
        "ALPT-051",
        "07/2024",
        "06/2026",
        "M/s. Alifecare Pharmacy Pvt Ltd, VPO-Barog, Teh & Distt. Solan (H.P.) -173212",
        "Dissolution of Telmisartan",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-24",
        "notice_id": "JUN-2025-cdsco_pdf-24",
        "product": "Telmisartan Tablets IP 40 mg",
        "batch": "ALPT-051",
        "test": "Dissolution of Telmisartan",
        "maker": "Alifecare Pharmacy Pvt Ltd",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 25,
      "bbox": {
        "left": 0.0652,
        "top": 0.5286,
        "width": 0.8512,
        "height": 0.0783
      },
      "cells": [
        "25.",
        "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection",
        "B.no: IEW1480C, IEW-1480B",
        "09/2024",
        "08/2026",
        "M/s. G.Pharmaceuticals, Vill. Mandhala, Tehsil: Baddi Distt.Solan (H.P.)",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-25",
        "notice_id": "JUN-2025-cdsco_pdf-25",
        "product": "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection",
        "batch": "B.no: IEW1480C, IEW-1480B",
        "test": "Particulate Matter and Description",
        "maker": "G.Pharmaceuticals",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 26,
      "bbox": {
        "left": 0.0652,
        "top": 0.6069,
        "width": 0.8512,
        "height": 0.0779
      },
      "cells": [
        "26.",
        "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection )",
        "B.no: IEW-1487C, IEW-1487B",
        "09/2024",
        "08/2026",
        "M/s. .G.Pharmaceuticals, Vill. Mandhala, Tehsil: Baddi Distt.Solan (H.P.)",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-26",
        "notice_id": "JUN-2025-cdsco_pdf-26",
        "product": "Vitamin C Injection IP and Vitamin B12, Folic Acid and Niacinamide Injection (Eldervit-12 Injection )",
        "batch": "B.no: IEW-1487C, IEW-1487B",
        "test": "Particulate Matter and Description",
        "maker": ".G.Pharmaceuticals",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 27,
      "bbox": {
        "left": 0.0652,
        "top": 0.6848,
        "width": 0.8512,
        "height": 0.0788
      },
      "cells": [
        "27.",
        "3% Sodium Chloride Injection USP",
        "G25B016",
        "02/2025",
        "01/2027",
        "M/s. Inven Pharmaceuticals Pvt. Ltd., Village Kalsada Khurd, District-Dhar (M.P.)- 454001",
        "Particulate Matter in Injections",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-27",
        "notice_id": "JUN-2025-cdsco_pdf-27",
        "product": "3% Sodium Chloride Injection USP",
        "batch": "G25B016",
        "test": "Particulate Matter in Injections",
        "maker": "Inven Pharmaceuticals Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 28,
      "bbox": {
        "left": 0.0652,
        "top": 0.7636,
        "width": 0.8512,
        "height": 0.0779
      },
      "cells": [
        "28.",
        "Ondansetron Injection IP (Ondson Inj.)",
        "P24L189",
        "11/2024",
        "10/2026",
        "M/s. Paksons Pharmaceuticals Private Limited, 36, Milestone, Delhi Rohtak Road, Sankhol, Bahadurgarh-124507, Haryana",
        "Particulate Matter and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-28",
        "notice_id": "JUN-2025-cdsco_pdf-28",
        "product": "Ondansetron Injection IP (Ondson Inj.)",
        "batch": "P24L189",
        "test": "Particulate Matter and Description",
        "maker": "Paksons Pharmaceuticals Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 29,
      "bbox": {
        "left": 0.0652,
        "top": 0.8414,
        "width": 0.8512,
        "height": 0.0783
      },
      "cells": [
        "29.",
        "Sitagliptin & Metformin Tablets 50mg + 1000mg (Sitajack-M)",
        "T-2672",
        "09/2024",
        "08/2026",
        "M/s. Jackson Laboratories Pvt.Ltd. 22-24, Majitha Road, Bye Pass, Amritsar- 143001(India)",
        "Assay of Sitagliptin",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-29",
        "notice_id": "JUN-2025-cdsco_pdf-29",
        "product": "Sitagliptin & Metformin Tablets 50mg + 1000mg (Sitajack-M)",
        "batch": "T-2672",
        "test": "Assay of Sitagliptin",
        "maker": "Jackson Laboratories Pvt.Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 3,
      "row": 30,
      "bbox": {
        "left": 0.0652,
        "top": 0.9198,
        "width": 0.8512,
        "height": 0.0382
      },
      "cells": [
        "30.",
        "Cefotaxime Sodium Injection IP 1g",
        "1172",
        "08/2023",
        "07/2025",
        "M/s. Hindustan Antibiotics Ltd., Pimpri,Pune-411018,India",
        "Water",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-30",
        "notice_id": "JUN-2025-cdsco_pdf-30",
        "product": "Cefotaxime Sodium Injection IP 1g",
        "batch": "1172",
        "test": "Water",
        "maker": "Hindustan Antibiotics Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 31,
      "bbox": {
        "left": 0.0656,
        "top": 0.0597,
        "width": 0.8517,
        "height": 0.0592
      },
      "cells": [
        "31.",
        "Amikacin Sulphate Injection IP (Lamic-500 Injection )",
        "L-24K-31H",
        "11/2024",
        "10/2026",
        "M/s. Inmac Laboratories, Bangsipura-142033 (Pb.)",
        "Particulate Matter, Assay and Description",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-31",
        "notice_id": "JUN-2025-cdsco_pdf-31",
        "product": "Amikacin Sulphate Injection IP (Lamic-500 Injection )",
        "batch": "L-24K-31H",
        "test": "Particulate Matter, Assay and Description",
        "maker": "Inmac Laboratories",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 32,
      "bbox": {
        "left": 0.0656,
        "top": 0.1189,
        "width": 0.8517,
        "height": 0.0774
      },
      "cells": [
        "32.",
        "Pantoprazole Sodium for Injection (K Pan-IV Injection)",
        "GD24L-27H",
        "12/2024",
        "11/2026",
        "M/s. Vellinton Healthcare, Trilokpur Road,Vill-Rampur Jattan, Kala-Amb-173030. Distt. Sirmour (H.P.)",
        "Sterility",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-32",
        "notice_id": "JUN-2025-cdsco_pdf-32",
        "product": "Pantoprazole Sodium for Injection (K Pan-IV Injection)",
        "batch": "GD24L-27H",
        "test": "Sterility",
        "maker": "Vellinton Healthcare",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 33,
      "bbox": {
        "left": 0.0656,
        "top": 0.1963,
        "width": 0.8517,
        "height": 0.117
      },
      "cells": [
        "33.",
        "Pantoprazole Gasrro- Resistant and Domperidone Prolonged Release Capsules IP (Prazentasure-DSR Capsules)",
        "NC24004",
        "09/2024",
        "08/2026",
        "M/s. Nexkem Pharmaceuticals Pvt. Ltd., Plot No. 119, HPSIDC Industrial Area Baddi, Dist. Solan (H.P.)-173205",
        "Dissolution of Pantoprazole in Buffer Stage",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-33",
        "notice_id": "JUN-2025-cdsco_pdf-33",
        "product": "Pantoprazole Gasrro- Resistant and Domperidone Prolonged Release Capsules IP (Prazentasure-DSR Capsules)",
        "batch": "NC24004",
        "test": "Dissolution of Pantoprazole in Buffer Stage",
        "maker": "Nexkem Pharmaceuticals Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 34,
      "bbox": {
        "left": 0.0656,
        "top": 0.3134,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "34.",
        "Diclofenac Sodium Injection IP (ZOR INJ.)",
        "P25L265",
        "02/2025",
        "01/2027",
        "M/s. Paksons Pharmaceuticals Private Limited, 36, Milestone, Delhi Rohtak Road, Sankhol, Bahadurgarh-124507, Haryana",
        "Extractable Volume",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-34",
        "notice_id": "JUN-2025-cdsco_pdf-34",
        "product": "Diclofenac Sodium Injection IP (ZOR INJ.)",
        "batch": "P25L265",
        "test": "Extractable Volume",
        "maker": "Paksons Pharmaceuticals Private Limited",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 35,
      "bbox": {
        "left": 0.0656,
        "top": 0.3917,
        "width": 0.8517,
        "height": 0.1359
      },
      "cells": [
        "35.",
        "Rabeprazole Sodium Injection IP",
        "MD23H12",
        "08/2023",
        "07/2025",
        "M/s. Martin & Brown Bio- Sciences Pvt.Ltd., K.No- 918/419, Malkumajra, Nalagarh Road, Baddi, Dist- Solan, HP-173205",
        "pH, Clarity of Solution, Uniformity of Weight, Particulate Matter and Assay of Rabeprazole Sodium",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-35",
        "notice_id": "JUN-2025-cdsco_pdf-35",
        "product": "Rabeprazole Sodium Injection IP",
        "batch": "MD23H12",
        "test": "pH, Clarity of Solution, Uniformity of Weight, Particulate Matter and Assay of Rabeprazole Sodium",
        "maker": "Martin & Brown Bio- Sciences Pvt.Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 36,
      "bbox": {
        "left": 0.0656,
        "top": 0.5276,
        "width": 0.8517,
        "height": 0.0788
      },
      "cells": [
        "36.",
        "Amoxycillin and Potassium Clavulanate Injection IP",
        "ACP-738A",
        "09/2023",
        "08/2025",
        "M/s. Pushkar Pharma, Kheri, Kala-Amb-173030. (H.P.)",
        "Assay of Potassium Clavulanate equivalent to Clavulanic Acid",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-36",
        "notice_id": "JUN-2025-cdsco_pdf-36",
        "product": "Amoxycillin and Potassium Clavulanate Injection IP",
        "batch": "ACP-738A",
        "test": "Assay of Potassium Clavulanate equivalent to Clavulanic Acid",
        "maker": "Pushkar Pharma",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 37,
      "bbox": {
        "left": 0.0656,
        "top": 0.6064,
        "width": 0.8517,
        "height": 0.1359
      },
      "cells": [
        "37.",
        "Methycobalamin, Calcitriol, Omega-3 Fatty Acids (EPA & DHA), Folic Acid, Boron, Calcium Carbonate Softgel Capsules (Biofil-Max Softgel Capsules )",
        "HPDJ24170",
        "10/2024",
        "09/2026",
        "M/s. Healthwise Pharma, VPO Bhud, Teh.Baddi, Distt-Solan (H.P.)-173205",
        "Assay of Docosahexaenoic Acid,Eicosapentaen oic acid",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-37",
        "notice_id": "JUN-2025-cdsco_pdf-37",
        "product": "Methycobalamin, Calcitriol, Omega-3 Fatty Acids (EPA & DHA), Folic Acid, Boron, Calcium Carbonate Softgel Capsules (Biofil-Max Softgel Capsules )",
        "batch": "HPDJ24170",
        "test": "Assay of Docosahexaenoic Acid,Eicosapentaen oic acid",
        "maker": "Healthwise Pharma",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 38,
      "bbox": {
        "left": 0.0656,
        "top": 0.7423,
        "width": 0.8517,
        "height": 0.0585
      },
      "cells": [
        "38.",
        "Paracetamol Intravenous Infusion (1.0% w/v)",
        "E25B026",
        "02/2025",
        "01/2028",
        "M/s. D.J. Laboratories Pvt. Ltd., 255, Sector-1, Industrial Area, Pithampur-454775",
        "Particulate Contamination",
        "CDL, Kolkata"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-38",
        "notice_id": "JUN-2025-cdsco_pdf-38",
        "product": "Paracetamol Intravenous Infusion (1.0% w/v)",
        "batch": "E25B026",
        "test": "Particulate Contamination",
        "maker": "D.J. Laboratories Pvt. Ltd.",
        "lab": "CDL, Kolkata"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 39,
      "bbox": {
        "left": 0.0656,
        "top": 0.8009,
        "width": 0.8517,
        "height": 0.059
      },
      "cells": [
        "39.",
        "Telmisartan Tablets IP 40 mg",
        "TLL-504",
        "01/2025",
        "12/2026",
        "Healers Lab Unit II, Plot No. 33, H.P.S.I.D.C., Extn., Baddi, Distt-Solan (H.P)",
        "Dissolution of Telmisartan",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-39",
        "notice_id": "JUN-2025-cdsco_pdf-39",
        "product": "Telmisartan Tablets IP 40 mg",
        "batch": "TLL-504",
        "test": "Dissolution of Telmisartan",
        "maker": "Healers Lab Unit II",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 40,
      "bbox": {
        "left": 0.0656,
        "top": 0.8598,
        "width": 0.8517,
        "height": 0.0585
      },
      "cells": [
        "40.",
        "Telmisartan Tablets IP 40 mg",
        "TLL-503",
        "01/2025",
        "12/2026",
        "M/s.Healers Lab Unit II, Plot No. 33, H.P.S.I.D.C., Extn., Baddi, Distt-Solan (H.P)",
        "Dissolution of Telmisartan",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-40",
        "notice_id": "JUN-2025-cdsco_pdf-40",
        "product": "Telmisartan Tablets IP 40 mg",
        "batch": "TLL-503",
        "test": "Dissolution of Telmisartan",
        "maker": "Healers Lab Unit II",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 4,
      "row": 41,
      "bbox": {
        "left": 0.0656,
        "top": 0.9184,
        "width": 0.8517,
        "height": 0.0383
      },
      "cells": [
        "41.",
        "Telmisartan Tablets IP (Telzasig 20)",
        "TEZC25001",
        "04/2025",
        "03/2027",
        "M/s.Signova Healthcare Pvt. Ltd (Unit-II), EPIP Silasundari, Ghopa, Amingaon, North Guwahati, Assam-781031",
        "Dissolution of Telmisartan",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-41",
        "notice_id": "JUN-2025-cdsco_pdf-41",
        "product": "Telmisartan Tablets IP (Telzasig 20)",
        "batch": "TEZC25001",
        "test": "Dissolution of Telmisartan",
        "maker": "Signova Healthcare Pvt. Ltd",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 42,
      "bbox": {
        "left": 0.0656,
        "top": 0.0591,
        "width": 0.8517,
        "height": 0.04
      },
      "notice": null,
      "merged_into": 41
    },
    {
      "page": 5,
      "row": 43,
      "bbox": {
        "left": 0.0656,
        "top": 0.0991,
        "width": 0.8517,
        "height": 0.117
      },
      "cells": [
        "42.",
        "Infusion Set-NV",
        "KT-071",
        "11/2024",
        "10/2027",
        "M/s. Medivision Healthcare, 84/4 Span Industrial complex. Second Floor, Phase-1, F Road, Opp. Kotak Mahindra Bank, G.I. D.C. Vatva, Ahmedabad- 382445",
        "Sterillity",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-43",
        "notice_id": "JUN-2025-cdsco_pdf-43",
        "product": "Infusion Set-NV",
        "batch": "KT-071",
        "test": "Sterillity",
        "maker": "Medivision Healthcare",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 44,
      "bbox": {
        "left": 0.0656,
        "top": 0.2161,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "43.",
        "Calcium & Vitamin D3 Tablets IP (Calciven-500)",
        "T-240267",
        "06/2024",
        "05/2026",
        "M/s. Sunlife Sciences,, 130, Kurdi, Jhabrera Road, Manglour, Roorkee, Distt. Haridwar (U.K.)",
        "Assay of Vitamin D3",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-44",
        "notice_id": "JUN-2025-cdsco_pdf-44",
        "product": "Calcium & Vitamin D3 Tablets IP (Calciven-500)",
        "batch": "T-240267",
        "test": "Assay of Vitamin D3",
        "maker": "Sunlife Sciences",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 45,
      "bbox": {
        "left": 0.0656,
        "top": 0.2945,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "44.",
        "Pantoprazole Tablets IP 20 mg (Opipan- 20)",
        "23G-T1503",
        "10/2023",
        "09/2025",
        "M/s. Orison Pharma International, Vill. Khari, Mauza Ogli, Kala Amb, Distt. Sirmour 173030 (H.P.)",
        "Dissolution in Acid Stage & Description",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-45",
        "notice_id": "JUN-2025-cdsco_pdf-45",
        "product": "Pantoprazole Tablets IP 20 mg (Opipan- 20)",
        "batch": "23G-T1503",
        "test": "Dissolution in Acid Stage & Description",
        "maker": "Orison Pharma International",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 46,
      "bbox": {
        "left": 0.0656,
        "top": 0.3728,
        "width": 0.8517,
        "height": 0.058
      },
      "cells": [
        "45.",
        "Azithromycin Tablets IP 500 mg.",
        "AYC-2407",
        "01/2024",
        "12/2025",
        "M/s.Apple Formulations Pvt. Ltd., Plot No.208, Kishanpur, Roorkee- 247667(U.K.)",
        "Dissolution of Azithromycin",
        "RDTL, Guwahati"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-46",
        "notice_id": "JUN-2025-cdsco_pdf-46",
        "product": "Azithromycin Tablets IP 500 mg.",
        "batch": "AYC-2407",
        "test": "Dissolution of Azithromycin",
        "maker": "Apple Formulations Pvt. Ltd.",
        "lab": "RDTL, Guwahati"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 47,
      "bbox": {
        "left": 0.0656,
        "top": 0.4309,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "46.",
        "Colestyramine BP",
        "SB43/001M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Loss on drying",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-47",
        "notice_id": "JUN-2025-cdsco_pdf-47",
        "product": "Colestyramine BP",
        "batch": "SB43/001M/ 24",
        "test": "Loss on drying",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 48,
      "bbox": {
        "left": 0.0656,
        "top": 0.5092,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "47.",
        "Cholestyramine Resin USP",
        "SB45/001M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Loss on drying",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-48",
        "notice_id": "JUN-2025-cdsco_pdf-48",
        "product": "Cholestyramine Resin USP",
        "batch": "SB45/001M/ 24",
        "test": "Loss on drying",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 49,
      "bbox": {
        "left": 0.0656,
        "top": 0.5875,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "48.",
        "Colestyramine EP",
        "SB48/001M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Loss on drying",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-49",
        "notice_id": "JUN-2025-cdsco_pdf-49",
        "product": "Colestyramine EP",
        "batch": "SB48/001M/ 24",
        "test": "Loss on drying",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 50,
      "bbox": {
        "left": 0.0656,
        "top": 0.6659,
        "width": 0.8517,
        "height": 0.0779
      },
      "cells": [
        "49.",
        "0.45 % w/v Sodium Chloride and 5% w/v Dextrose Injection I.P. (0.45 % DNS), 500 ml",
        "S3BX05",
        "11/2024",
        "10/2026",
        "M/s.Swaroop Pharmaceuticals Pvt. Ltd., A-10, Tala Nagari Industiral Area, Aligarh 202001.",
        "Test for Sterility",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-50",
        "notice_id": "JUN-2025-cdsco_pdf-50",
        "product": "0.45 % w/v Sodium Chloride and 5% w/v Dextrose Injection I.P. (0.45 % DNS), 500 ml",
        "batch": "S3BX05",
        "test": "Test for Sterility",
        "maker": "Swaroop Pharmaceuticals Pvt. Ltd.",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 51,
      "bbox": {
        "left": 0.0656,
        "top": 0.7437,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "50.",
        "Sodium Polystyrene Sulfonate EP",
        "SC42/048M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Loss on drying",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-51",
        "notice_id": "JUN-2025-cdsco_pdf-51",
        "product": "Sodium Polystyrene Sulfonate EP",
        "batch": "SC42/048M/ 24",
        "test": "Loss on drying",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 52,
      "bbox": {
        "left": 0.0656,
        "top": 0.8221,
        "width": 0.8517,
        "height": 0.0783
      },
      "cells": [
        "51.",
        "Sodium Polystyrene Sulfonate USP",
        "SC25/048M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Water determination",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-52",
        "notice_id": "JUN-2025-cdsco_pdf-52",
        "product": "Sodium Polystyrene Sulfonate USP",
        "batch": "SC25/048M/ 24",
        "test": "Water determination",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 5,
      "row": 53,
      "bbox": {
        "left": 0.0656,
        "top": 0.9004,
        "width": 0.8517,
        "height": 0.0388
      },
      "cells": [
        "52.",
        "Sodium Polystyrene Sulfonate BP",
        "SC27/048M/ 24",
        "07/2024",
        "07/2029",
        "M/s. Phaex Polymers Private Limited Plot No. : F-10, MIDC, Murbad, Dist- Thane-421401, Maharastra.",
        "Loss on drying",
        "CDTL-Mumbai"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-53",
        "notice_id": "JUN-2025-cdsco_pdf-53",
        "product": "Sodium Polystyrene Sulfonate BP",
        "batch": "SC27/048M/ 24",
        "test": "Loss on drying",
        "maker": "Phaex Polymers Private Limited",
        "lab": "CDTL-Mumbai"
      },
      "merged_into": null
    },
    {
      "page": 6,
      "row": 54,
      "bbox": {
        "left": 0.0667,
        "top": 0.0585,
        "width": 0.8506,
        "height": 0.0401
      },
      "notice": null,
      "merged_into": 53
    },
    {
      "page": 6,
      "row": 55,
      "bbox": {
        "left": 0.0667,
        "top": 0.0986,
        "width": 0.8506,
        "height": 0.0783
      },
      "cells": [
        "53.",
        "Nitrofurantoin Tablets I.P 100 mg",
        "NFDT1201",
        "10/2024",
        "09/2026",
        "M/s. Unicure India Ltd., C - 21, 22 & 23, Sector- 3, Noida - 201301, Distt. : Gautam Budh Nagar (U.P.)",
        "Dissolution",
        "CDTL Indore"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-55",
        "notice_id": "JUN-2025-cdsco_pdf-55",
        "product": "Nitrofurantoin Tablets I.P 100 mg",
        "batch": "NFDT1201",
        "test": "Dissolution",
        "maker": "Unicure India Ltd.",
        "lab": "CDTL Indore"
      },
      "merged_into": null
    },
    {
      "page": 6,
      "row": 56,
      "bbox": {
        "left": 0.0667,
        "top": 0.177,
        "width": 0.8506,
        "height": 0.0595
      },
      "cells": [
        "54.",
        "Glipizide & Metformin Tablets I.P",
        "Z24-011",
        "01/2024",
        "12/2026",
        "M/s. Zee Laboratories Ltd., Behind 47, Industrial Area, Paonta sahib - 173025",
        "Description",
        "CDTL Indore"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-56",
        "notice_id": "JUN-2025-cdsco_pdf-56",
        "product": "Glipizide & Metformin Tablets I.P",
        "batch": "Z24-011",
        "test": "Description",
        "maker": "Zee Laboratories Ltd.",
        "lab": "CDTL Indore"
      },
      "merged_into": null
    },
    {
      "page": 6,
      "row": 57,
      "bbox": {
        "left": 0.0667,
        "top": 0.2364,
        "width": 0.8506,
        "height": 0.1156
      },
      "cells": [
        "55.",
        "Cefpodoxime Dispersible Tablets 200 mg (Xpocef 200 DT)",
        "XCT24078C",
        "11/2024",
        "10/2026",
        "M/s.Xperia Creation, Survey No. 915/2, Block Part- A, Jetalpur Pirana Road, At & Post.-Girmatha Village, Tal.- Daskori, Dist-Ahmedabad- 382425, Gujarat.",
        "Uniformity of Dispersion",
        "CDTL, Hyderabad"
      ],
      "notice": {
        "pk": "cdsco_nsq#JUN-2025-cdsco_pdf-57",
        "notice_id": "JUN-2025-cdsco_pdf-57",
        "product": "Cefpodoxime Dispersible Tablets 200 mg (Xpocef 200 DT)",
        "batch": "XCT24078C",
        "test": "Uniformity of Dispersion",
        "maker": "Xperia Creation",
        "lab": "CDTL, Hyderabad"
      },
      "merged_into": null
    }
  ]
};
