/**
 * Real demo data for /kit, Storybook and the video (read from the live API and the recorded
 * ingest bundle on 20 Sep 2026). Notices are the API objects as returned (a few unused fields
 * dropped). Poll times are the 15:08 IST snapshot every v3 mockup uses.
 * Generated by v3 scratch script gen_fixtures.py; do not hand-edit values.
 */
import { apiExamples } from "./apiRequest";
import type { CdscoMonth, FeedFilters, HouseholdCheck, Notice, NoticeGroup, PinnedAlert, Stats, TryItResult } from "./types";

/** Page clock for every fixture: 20 Sep 2026, 15:08:40 IST. */
export const fixtureNow = "2026-09-20T09:38:40Z";

/** GET /v1/stats (shape as returned; US poll times set to the 15:08 IST snapshot). */
export const stats: Stats = {
  "total": 4868,
  "sources_count": 4,
  "sources": [
    {
      "source": "cdsco_nsq",
      "label": "CDSCO",
      "count": 2696,
      "health": "healthy",
      "last_run_at": "2026-09-19T18:24:32Z",
      "last_success_at": "2026-09-19T18:24:32Z",
      "last_error": null,
      "polls_every": "1 day",
      "pollers": [
        {
          "name": "cdsco_portal",
          "last_run_at": "2026-09-19T18:24:32Z",
          "last_success_at": "2026-09-19T18:24:32Z",
          "last_error": null,
          "degraded": false,
          "last_counts": {
            "updated": 0,
            "unchanged": 239,
            "created": 0,
            "fetched": 239,
            "upserted": 0
          }
        },
        {
          "name": "cdsco_pdf",
          "last_run_at": "2026-09-19T19:22:50Z",
          "last_success_at": "2026-09-19T19:22:50Z",
          "last_error": null,
          "degraded": false,
          "last_counts": {
            "created": 0,
            "upserted": 0,
            "unchanged": 55,
            "rows_in": 57,
            "notices_out": 55,
            "updated": 0
          }
        }
      ]
    },
    {
      "source": "cpsc",
      "label": "CPSC",
      "count": 1852,
      "health": "healthy",
      "last_run_at": "2026-09-20T09:38:30Z",
      "last_success_at": "2026-09-20T09:38:30Z",
      "last_error": null,
      "polls_every": "15 min",
      "pollers": [
        {
          "name": "cpsc",
          "last_run_at": "2026-09-20T09:38:30Z",
          "last_success_at": "2026-09-20T09:38:30Z",
          "last_error": null,
          "degraded": false,
          "last_counts": {
            "updated": 0,
            "skipped": 0,
            "fetched": 50,
            "upserted": 0,
            "unchanged": 50,
            "created": 0
          }
        }
      ]
    },
    {
      "source": "nhtsa",
      "label": "NHTSA",
      "count": 38,
      "health": "healthy",
      "last_run_at": "2026-09-20T09:38:04Z",
      "last_success_at": "2026-09-20T09:38:04Z",
      "last_error": null,
      "polls_every": "15 min",
      "pollers": [
        {
          "name": "nhtsa",
          "last_run_at": "2026-09-20T09:38:04Z",
          "last_success_at": "2026-09-20T09:38:04Z",
          "last_error": null,
          "degraded": false,
          "last_counts": {
            "fetched": 54,
            "created": 0,
            "updated": 0,
            "upserted": 0,
            "unchanged": 54
          }
        }
      ]
    },
    {
      "source": "openfda",
      "label": "openFDA",
      "count": 282,
      "health": "healthy",
      "last_run_at": "2026-09-20T09:37:57Z",
      "last_success_at": "2026-09-20T09:37:57Z",
      "last_error": null,
      "polls_every": "15 min",
      "pollers": [
        {
          "name": "openfda",
          "last_run_at": "2026-09-20T09:37:57Z",
          "last_success_at": "2026-09-20T09:37:57Z",
          "last_error": null,
          "degraded": false,
          "last_counts": {
            "unchanged": 221,
            "created": 0,
            "upserted": 0,
            "skipped": 0,
            "updated": 0,
            "fetched": 221
          }
        }
      ]
    }
  ],
  "cdsco_latest": {
    "month": "JUL-2026",
    "count": 239,
    "published_at": "2026-07-01",
    "complete": true
  },
  "last_poll_at": "2026-09-20T09:38:30Z",
  "generated_at": "2026-09-20T09:38:40Z"
};

/** last_poll_at + 15 min → "next at 15:23" */
export const nextPollAt = "2026-09-20T09:53:30Z";

/** public/data/cdsco-months.json: CDSCO notices per row_ref.month (counted from all 2,696 CDSCO notices). */
export const cdscoMonths: CdscoMonth[] = [{"month": "SEP-2025", "count": 112}, {"month": "OCT-2025", "count": 211}, {"month": "NOV-2025", "count": 216}, {"month": "DEC-2025", "count": 175}, {"month": "JAN-2026", "count": 218}, {"month": "FEB-2026", "count": 217}, {"month": "MAR-2026", "count": 190}, {"month": "APR-2026", "count": 121}, {"month": "MAY-2026", "count": 162}, {"month": "JUN-2026", "count": 193}, {"month": "JUL-2026", "count": 239}];

/** Notices shown in the feed mockups, as returned by GET /v1/notices/{id}. */
export const notices = {
  "aceclofenac": {
    "pk": "cdsco_nsq#JUL-2026-cdsco_portal-005f85bb4ee1",
    "source": "cdsco_nsq",
    "notice_id": "JUL-2026-cdsco_portal-005f85bb4ee1",
    "title": "Aceclofenac & Paracetamol Tablets IP — failed CDSCO quality test, JUL-2026 alert, row 129",
    "product": "Aceclofenac & Paracetamol Tablets IP",
    "brand": "Oxford Pharma",
    "batches": [
      "MT250239"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": {
      "page": null,
      "row": 129,
      "month": "JUL-2026"
    },
    "hazard_or_failed_test": "Content of Aceclofenac (82.94%)",
    "remedy": null,
    "published_at": "2026-07-01",
    "first_seen_at": "2026-09-18T18:40:45Z",
    "url": "https://cdscoonline.gov.in/CDSCO/viewPublicNSQDrug",
    "raw_excerpt": "Aceclofenac & Paracetamol Tablets IP | MT250239 | Jun-2025 | May-2028 | Oxford Pharma, Puhana Chowk, Roorkee, Distt. Haridwar-247667 (U.K) | Content of Aceclofenac (82.94%) | State Lab | Drugs Testing Laboratory, Madurai-19 | JUL-2026",
    "mfg_date": "Jun-2025",
    "exp_date": "May-2028",
    "lab": "Drugs Testing Laboratory, Madurai-19",
    "adapter": "cdsco_portal"
  },
  "paracetamolYuventis": {
    "pk": "cdsco_nsq#JUL-2026-cdsco_portal-b401248faa09",
    "source": "cdsco_nsq",
    "notice_id": "JUL-2026-cdsco_portal-b401248faa09",
    "title": "Paracet amol Tablets IP 650 mg — failed CDSCO quality test, JUL-2026 alert, row 42",
    "product": "Paracet amol Tablets IP 650 mg",
    "brand": "Yuventis Life Sciences",
    "batches": [
      "YT-250671E"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": {
      "month": "JUL-2026",
      "row": 42,
      "page": null
    },
    "hazard_or_failed_test": "Dissolution Test",
    "remedy": null,
    "published_at": "2026-07-01",
    "first_seen_at": "2026-09-18T18:40:43Z",
    "url": "https://cdscoonline.gov.in/CDSCO/viewPublicNSQDrug",
    "raw_excerpt": "Paracet amol Tablets IP 650 mg | YT-250671E | Oct-2025 | Sep-2027 | Yuventis Life Sciences, Promoted by Medvexl, Plot No.7 & Ext. Phase Ill, HPSIDC, Baddi, Dist Solan | Dissolution Test | State Lab | SDTL,Andhra Pradesh, Vijayawada | JUL-2026",
    "mfg_date": "Oct-2025",
    "exp_date": "Sep-2027",
    "lab": "SDTL,Andhra Pradesh, Vijayawada",
    "adapter": "cdsco_portal"
  },
  "metformin": {
    "pk": "cdsco_nsq#JUL-2026-cdsco_portal-ba549b38ea2f",
    "source": "cdsco_nsq",
    "notice_id": "JUL-2026-cdsco_portal-ba549b38ea2f",
    "title": "Metformin Hydrochloride Prolonged-Released and Glimepiride Tablets IP — failed CDSCO quality test, JUL-2026 alert, row 70",
    "product": "Metformin Hydrochloride Prolonged-Released and Glimepiride Tablets IP",
    "brand": "USV Private Limited",
    "batches": [
      "60002727"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": {
      "page": null,
      "month": "JUL-2026",
      "row": 70
    },
    "hazard_or_failed_test": "The sample does not conform to claim as per Manufacture's Specification with respect to the test for Dissolution of Metformin Hydrochloride.",
    "remedy": null,
    "published_at": "2026-07-01",
    "first_seen_at": "2026-09-18T18:40:44Z",
    "url": "https://cdscoonline.gov.in/CDSCO/viewPublicNSQDrug",
    "raw_excerpt": "Metformin Hydrochloride Prolonged-Released and Glimepiride Tablets IP | 60002727 | Mar-2026 | Feb-2028 | USV Private Limited,Plot No. 538 to 540, 597 to 618, 619 to 625, GIDC Indl. Area-Savli, Taluka-Savli, Manjusar, Vadodara - 391 775. | The sample does not conform to claim as per Manufacture's Specification with respect to the test for Dissolution of Metformin Hydrochloride. | CDSCO Labs | CDTL, Indore | JUL-2026",
    "mfg_date": "Mar-2026",
    "exp_date": "Feb-2028",
    "lab": "CDTL, Indore",
    "adapter": "cdsco_portal"
  },
  "paracetamolFt5427": {
    "pk": "cdsco_nsq#JUL-2026-cdsco_portal-b75cfffe3713",
    "source": "cdsco_nsq",
    "notice_id": "JUL-2026-cdsco_portal-b75cfffe3713",
    "title": "Paracetamol Tablets IP 650mg — failed CDSCO quality test, JUL-2026 alert, row 12",
    "product": "Paracetamol Tablets IP 650mg",
    "brand": "Forgo Pharmaceuticals",
    "batches": [
      "FT5427"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": {
      "row": 12,
      "month": "JUL-2026",
      "page": null
    },
    "hazard_or_failed_test": "The sample does not conforms to the I.P. with respect to Dissolution Test.",
    "remedy": null,
    "published_at": "2026-07-01",
    "first_seen_at": "2026-09-18T18:40:43Z",
    "url": "https://cdscoonline.gov.in/CDSCO/viewPublicNSQDrug",
    "raw_excerpt": "Paracetamol Tablets IP 650mg | FT5427 | Oct-2025 | Sep-2027 | Forgo Pharmaceuticals, 27, DIC Ind Area, Barotiwala, Teh: Baddi, Distt. Solan (HP) 174103 | The sample does not conforms to the I.P. with respect to Dissolution Test. | State Lab | DTL Bikaner | JUL-2026",
    "mfg_date": "Oct-2025",
    "exp_date": "Sep-2027",
    "lab": "DTL Bikaner",
    "adapter": "cdsco_portal"
  },
  "sauna": {
    "pk": "cpsc#10984",
    "source": "cpsc",
    "notice_id": "10984",
    "title": "Sauna360 Recalls Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits Due to Risk of Serious Injury or Death from Fire and Burn Hazards",
    "product": "Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits",
    "brand": "Sauna360 Inc.",
    "batches": [],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "The infrared panels in the saunas and kits can short circuit, causing them to overheat, posing a risk of serious injury from fire and burn hazards.",
    "remedy": "Consumers should stop using the infrared and hybrid saunas immediately and contact Sauna360 to schedule a free in-home repair from a professional installer.; Repair",
    "published_at": "2026-09-17",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Sauna360-Recalls-Infrared-Saunas-Hybrid-Infrared-Saunas-and-Infrared-Kits-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-and-Burn-Hazards",
    "raw_excerpt": "Sauna360 Recalls Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits Due to Risk of Serious Injury or Death from Fire and Burn Hazards\nThis recall involves various infrared and hybrid sauna models and infrared (IR) kits. Customers who purchased custom rooms built with IR panels can check for the words \"Saunalogic,\" \"Infralogic,\" \"Carbonflex,\" or \"Tylö\" on their control panel or locate their product manual. Customers who purchased pre-configured infrared sauna rooms can identify their product by the brand badge on the front frame panel, the control panel, the manual or the logo handle. Consumers can also find the serial number located under the lower bench or on the wall under the upper bench depending on the unit and provide Sauna360 the serial number to determine if they have a recalled sauna. The IR sauna kits with panels, along with the following sauna model numbers, are included in this recall:\nInfrared Saunas, Hybrid Infrared Saunas and Infrared Kits",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "grill": {
    "pk": "cpsc#10986",
    "source": "cpsc",
    "notice_id": "10986",
    "title": "Char-Broil Recalls Bistro Pro Electric Grills Due to Risk of Electric Shock",
    "product": "Charbroil Bistro Pro Electric Grills",
    "brand": "Char-Broil LLC",
    "batches": [
      "2510",
      "2511",
      "2512"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "The grounding wire for the grill’s heating element can disconnect and lose fault protection, posing an electric shock hazard.",
    "remedy": "Consumers should stop using the recalled electric grills immediately and contact Char-Broil for a free repair kit. Consumers will be asked to register at www.charbroil.com/BistroProFix to receive repair instructions, a screwdriver, a wrench, screws and a label to affix to the grill after repair. Char-Broil is offering a digital $25 gift card, valid at participating retailers, to consumers who provide photo documentation of the completed repair.; Repair",
    "published_at": "2026-09-17",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Char-Broil-Recalls-Bistro-Pro-Electric-Grills-Due-to-Risk-of-Electric-Shock",
    "raw_excerpt": "Char-Broil Recalls Bistro Pro Electric Grills Due to Risk of Electric Shock\nThis recall involves the Charbroil Bistro Pro Electric Grills with model descriptions Bistro Pro Electric Grill & Griddle + Charcoal, Bistro Electric Grill + Charcoal and Bistro Pro Tabletop Electric Grill. The grills were sold in full-size and tabletop configurations in Black (black and gray), Red, Blackout (all black) and Emerald (green). The units have a \"CB\" logo plate on the front of the lid and \"CHARBROIL\" printed on the front control panel. The product label listing the model and serial number, including a four-digit manufacturing date code in year and month (YYMM) format, is located on the bottom shelf of full-size grills and on the side bar of tabletop models. Only Bistro Pro Electric Grills with date codes of 2510 (Oct-2025), 2511 (Nov-2025) and 2512 (Dec-2025) are included in this recall.\nCharbroil Bistro Pro Electric Grills",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "busyBoard": {
    "pk": "cpsc#10982",
    "source": "cpsc",
    "notice_id": "10982",
    "title": "Esjay US Recalls Toddler Busy Board Montessori Toys Due to Risk of Serious Injury or Death from Choking; Violates Small Parts Ban",
    "product": "Esjay Toddler Busy Board Montessori Toys",
    "brand": "Shenzhen Yishijie Technology Co., Ltd., dba Esjay US",
    "batches": [],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "The recalled toy violates the small parts ban because the product is for children under three years of age and the red knobs can detach, posing a deadly choking hazard.",
    "remedy": "Consumers should take the recalled toy away from children, stop using it immediately and contact Esjay for instructions on the repair. Consumers will be asked to unzip the page with red knobs, write “RECALLED” on both sides of the page and throw it away. Send a photo of the disposed page to Esjay US at esjay-service@outlook.com to receive a replacement page.; Repair",
    "published_at": "2026-09-17",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Esjay-US-Recalls-Toddler-Busy-Board-Montessori-Toys-Due-to-Risk-of-Serious-Injury-or-Death-from-Choking-Violates-Small-Parts-Ban",
    "raw_excerpt": "Esjay US Recalls Toddler Busy Board Montessori Toys Due to Risk of Serious Injury or Death from Choking; Violates Small Parts Ban\nThis recall involves Esjay Toddler Busy Board Montessori Toys. The busy boards are made of blue felt, have carrying handles, elastic cords and button closures. The front is printed with various cartoon dinosaurs, and the back is printed with 26 small squares, each corresponding to a letter of the alphabet. Each square contains the letter and a cartoon animal. The busy boards have five pages in total and the page with red knobs is the second page.\nEsjay Toddler Busy Board Montessori Toys",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "mattress": {
    "pk": "cpsc#10981",
    "source": "cpsc",
    "notice_id": "10981",
    "title": "Regfear Recalls BedsPick Mattresses Due to Risk of Serious Injury or Death from Fire; Violate Mandatory Flammability Standard for Mattresses",
    "product": "BedsPick Mattresses",
    "brand": "BedsPick Mattresses",
    "batches": [],
    "model": "SME004",
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "The mattresses violate the mandatory flammability standard for mattresses, posing a risk of serious injury or death from fire.",
    "remedy": "Consumers should stop using the recalled mattresses immediately and contact Regfear for a full refund. Consumers will be asked to destroy the mattress, write in permanent marker “Recalled,” on the mattress’ top surface and email a photo of the destroyed mattress to BedsPickRecall@outlook.com. Consumers should then dispose of the recalled product. The refund will be issued after Regfear receives photos and written confirmation of disposal.; Refund",
    "published_at": "2026-09-17",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Regfear-Recalls-BedsPick-Mattresses-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-Violate-Mandatory-Flammability-Standard-for-Mattresses",
    "raw_excerpt": "Regfear Recalls BedsPick Mattresses Due to Risk of Serious Injury or Death from Fire; Violate Mandatory Flammability Standard for Mattresses\nThis recall involves two styles of BedsPick branded Mattresses. The mattresses are 12 inches thick and sold in queen size. They have a white top and purple sides or a white top and gray sides and were sold compressed in a box. Prototype ID \"AMGSW066\" or \"AMGSW067\" and model numbers \"SME004\" or \"AMG005197_12_Q_GLT\" are printed on a sewn-in white label located on one side of the mattress.\nBedsPick Mattresses",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "helmet": {
    "pk": "cpsc#10978",
    "source": "cpsc",
    "notice_id": "10978",
    "title": "Tongyang Cycling Recalls Basecamp Bicycle Helmets Due to Risk of Serious Injury or Death from Head Injury; Violate Mandatory Standard for Bicycle Helmets",
    "product": "Basecamp Bike Helmets",
    "brand": "Basecamp Bike",
    "batches": [],
    "model": "HT-10",
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "The recalled helmets violate the mandatory safety standard for bicycle helmets because the helmets do not comply with the impact attenuation, positional stability and certification requirements. The helmets can fail to protect the user in the event of a crash, posing a serious risk of injury or death due to head injury. In addition, the helmets have a button cell battery that does not bear the warning labels required by Reese’s Law. If button cell or coin batteries are swallowed, the ingested batteries can cause serious injuries, including internal chemical burns, and death.",
    "remedy": "Consumers should stop using the helmets immediately and contact Tongyang Cycling for a full refund. Consumers will be asked to destroy the recalled helmet by cutting the straps and send a photo of the destroyed helmet to tongyangshangwuus@hotmail.com. Consumers should then dispose of the recalled product. Note: Button cell batteries are hazardous. Batteries should be disposed of or recycled by following local hazardous waste procedures.; Refund",
    "published_at": "2026-09-17",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Tongyang-Cycling-Recalls-Basecamp-Bicycle-Helmets-Due-to-Risk-of-Serious-Injury-or-Death-from-Head-Injury-Violate-Mandatory-Standard-for-Bicycle-Helmets",
    "raw_excerpt": "Tongyang Cycling Recalls Basecamp Bicycle Helmets Due to Risk of Serious Injury or Death from Head Injury; Violate Mandatory Standard for Bicycle Helmets\nThis recall involves Basecamp-branded bicycle helmets, model HT-10. The helmets were sold in green and black and in size medium/large (M/L), fitting a head circumference of about 22.44 to 24.41 inches. The helmets have red padding, black and red straps, a black and red buckle and a black and red fit-adjusting knob at the back. \"Basecamp\" is printed on the sides of the helmet and “\"HT-10\" on a label inside of the helmet.\nBasecamp Bike Helmets",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "tiguan": {
    "pk": "nhtsa#26V587000",
    "source": "nhtsa",
    "notice_id": "26V587000",
    "title": "Volkswagen Tiguan: ELECTRICAL SYSTEM:BODY CONTROL MODULE:SOFTWARE",
    "product": "Volkswagen Tiguan",
    "brand": "Volkswagen",
    "batches": [],
    "model": "Tiguan",
    "vehicles": [
      {
        "year_to": 2025,
        "year_from": 2025,
        "model": "tiguan",
        "make": "volkswagen"
      }
    ],
    "row_ref": null,
    "hazard_or_failed_test": "ELECTRICAL SYSTEM:BODY CONTROL MODULE:SOFTWARE: An unexpected engine stall, loss of exterior lighting or warning lights, or failure of the rearview camera system can increase the risk of a crash.",
    "remedy": "Dealers will update the body control module (BCM) software, free of charge. Owner notification letters are expected to be mailed November 6, 2026. Owners may contact Volkswagen customer service at 1-800-893-5298. Volkswagen's number for this recall is 57KL. Vehicle Identification Numbers (VINs) involved in this recall became searchable on NHTSA.gov on September 17, 2026.",
    "published_at": "2026-09-10",
    "first_seen_at": "2026-09-18T18:42:23Z",
    "url": "https://www.nhtsa.gov/recalls?nhtsaId=26V587000",
    "raw_excerpt": "Volkswagen Group of America, Inc. (Volkswagen) is recalling certain 2025 Tiguan vehicles. A software error may cause the body control module (BCM) system to reset. This may result in the ignition switching off, resulting in an engine stall. It can also lead to a loss of certain controls, warning lights, exterior lighting, or failure of the rearview camera system. As such, these vehicles fail to comply with the requirements of Federal Motor Vehicle Safety Standard (FMVSS) numbers 101, \"Controls and Displays,\" and 102, \"Transmission shift lever sequence, starter interlock, and transmission braking effect,\" as well as FMVSS numbers 111 and 108.\nAn unexpected engine stall, loss of exterior lighting or warning lights, or failure of the rearview camera system can increase the risk of a crash.\nDealers will update the body control module (BCM) software, free of charge. Owner notification letters are expected to be mailed November 6, 2026. Owners may contact Volkswagen customer service at 1-800-893-5298. Volkswagen's number for this recall is 57KL. Vehicle Identification Numbers (VINs) involved in this recall became searchable on NHTSA.gov on September 17, 2026.",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "agaRange": {
    "pk": "cpsc#10968",
    "source": "cpsc",
    "notice_id": "10968",
    "title": "Dual Fuel Ranges Recalled Due to Risk of Serious Injury or Death from Fire or Explosion Hazards; Manufactured by AGA Rangemaster",
    "product": "AGA Elise and Mercury Series Freestanding Dual Fuel Ranges and La Cornue CornuFé 90 and CornuFé 110 Series Freestanding Dual Fuel Ranges",
    "brand": "AGA Rangemaster Limited",
    "batches": [],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "Dual Fuel Ranges with a missing cap from the gas test port can cause a gas leak,​ posing a risk of serious injury or death from fire or explosion hazards.",
    "remedy": "Consumers should shut off the gas supply to avoid the risk of gas leak immediately and contact AGA Rangemaster. Consumers should promptly determine if their range is subject to recall by locating the model/serial number on the rating plate (on the bottom panel under the storage drawer) and visiting the Recall webpage at www.lacornueusa.com/testcap-recall or www.agarangeusa.com/testcap-recall. If subject to the recall, consumers should contact AGA Rangemaster for a free inspection and repair by a certified technician. Consumers can continue to use only the electric oven sections of the range. The gas surface burners cannot be used.; Repair",
    "published_at": "2026-09-10",
    "first_seen_at": "2026-09-18T18:41:44Z",
    "url": "https://cpsc.gov/Recalls/2026/Dual-Fuel-Ranges-Recalled-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-or-Explosion-Hazards-Manufactured-by-AGA-Rangemaster",
    "raw_excerpt": "Dual Fuel Ranges Recalled Due to Risk of Serious Injury or Death from Fire or Explosion Hazards; Manufactured by AGA Rangemaster\nThis recall involves freestanding AGA Elise and Mercury Series Dual Fuel Ranges, in 36- and 48-inch widths and freestanding La Cornue CornuFé Series Dual Fuel Ranges in 36- and 43-inch widths manufactured between March 19, 2025 and July 24, 2026. All units have gas surface burners, set for Natural or LP gas, with one to three electric ovens depending on size. The products are sold in stainless steel, white and 13 other colors, which can be found at www.agarangeusa.com and www.lacornueusa.com. All colors, trim options and gas types (Natural or LP) are included. The serial number is on the rating plate, which is located on the bottom panel of the unit under the storage drawer.\nAGA Elise and Mercury Series Freestanding Dual Fuel Ranges and La Cornue CornuFé 90 and CornuFé 110 Series Freestanding Dual Fuel Ranges",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "jeepCompass": {
    "pk": "nhtsa#24V436000",
    "source": "nhtsa",
    "notice_id": "24V436000",
    "title": "Jeep Compass: BACK OVER PREVENTION: SENSING SYSTEM: CAMERA",
    "product": "Jeep Compass",
    "brand": "Jeep",
    "batches": [],
    "model": "Compass",
    "vehicles": [
      {
        "make": "jeep",
        "year_from": 2022,
        "year_to": 2022,
        "model": "compass"
      },
      {
        "year_from": 2023,
        "make": "jeep",
        "year_to": 2023,
        "model": "compass"
      }
    ],
    "row_ref": null,
    "hazard_or_failed_test": "BACK OVER PREVENTION: SENSING SYSTEM: CAMERA: A rearview camera image that does not display decreases the driver's visibility, increasing the risk of a crash.",
    "remedy": "Dealers will update the radio software or the software will be OTA, \"Over-The-Air,\" free of charge. Owner notification letters were mailed beginning July 9, 2024. Owners may contact FCA US, LLC customer service at 1-800-853-1403. FCA US, LLC's numbers for this recall are 66B and 79B.",
    "published_at": "2024-06-13",
    "first_seen_at": "2026-09-18T18:42:19Z",
    "url": "https://www.nhtsa.gov/recalls?nhtsaId=24V436000",
    "raw_excerpt": "Chrysler (FCA US, LLC) is recalling certain 2021-2022 Dodge Durango, 2021-2023 Chrysler Pacifica, Jeep Grand Cherokee L, 2022 Ram 1500, 2500, 3500, Chrysler Voyager, 2022-2023 Jeep Compass, Grand Cherokee, Wagoneer, Grand Wagoneer, and Ram Promaster vehicles. The radio software may prevent the rearview image from displaying. As such, these vehicles fail to comply with the requirements of Federal Motor Vehicle Safety Standard number 111, \"Rear Visibility.\"\nA rearview camera image that does not display decreases the driver's visibility, increasing the risk of a crash.\nDealers will update the radio software or the software will be OTA, \"Over-The-Air,\" free of charge. Owner notification letters were mailed beginning July 9, 2024. Owners may contact FCA US, LLC customer service at 1-800-853-1403. FCA US, LLC's numbers for this recall are 66B and 79B.\nOwners may also contact the National Highway Traffic Safety Administration Vehicle Safety Hotline at 1-888-327-4236 (TTY 1-800-424-9153), or go to www.nhtsa.gov.",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "trokendi": {
    "pk": "openfda#D-0833-2026",
    "source": "openfda",
    "notice_id": "D-0833-2026",
    "title": "drug recall: Trokendi XR, (topiramate) extended-release capsules, 50 mg, 30 Capsules, Rx only, Manufactured by: C",
    "product": "Trokendi XR, (topiramate) extended-release capsules, 50 mg, 30 Capsules, Rx only, Manufactured by: Catalent Pharma Solutions, Winchester, KY 40391 USA, Manufactured for: Supernus Pharmaceuticals, Inc., Rockville, MD 20850 USA, NDC 17772-102-30.",
    "brand": "TROKENDI XR",
    "batches": [
      "2145283"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "Failed dissolution specifications.",
    "remedy": null,
    "published_at": "2026-09-09",
    "first_seen_at": "2026-09-18T18:42:34Z",
    "url": "https://api.fda.gov/drug/enforcement.json?search=recall_number:%22D-0833-2026%22",
    "raw_excerpt": "Trokendi XR, (topiramate) extended-release capsules, 50 mg, 30 Capsules, Rx only, Manufactured by: Catalent Pharma Solutions, Winchester, KY 40391 USA, Manufactured for: Supernus Pharmaceuticals, Inc., Rockville, MD 20850 USA, NDC 17772-102-30.\nFailed dissolution specifications.\nLot# 2145283, Exp Date: 31-Mar-2030.",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "mycophenolate": {
    "pk": "openfda#D-0830-2026",
    "source": "openfda",
    "notice_id": "D-0830-2026",
    "title": "drug recall: Carton label: Mycophenolate Mofetil for injection, USP, 500 mg/vial, Sterile, 4 Single Dose Vials, R",
    "product": "Carton label: Mycophenolate Mofetil for injection, USP, 500 mg/vial, Sterile, 4 Single Dose Vials, Rx only, Manufactured for: Mylan Institutional LLC, Morgantown, WV 26505, Made in India, NDC 67457-386-81. Vial Label: Mycophenolate Mofetil for injection, USP, 500 mg/vial, Sterile, Single Dose Vial, ",
    "brand": "MYCOPHENOLATE MOFETIL",
    "batches": [
      "3242616"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "Failed Dissolution Specifications",
    "remedy": null,
    "published_at": "2026-09-09",
    "first_seen_at": "2026-09-18T18:42:34Z",
    "url": "https://api.fda.gov/drug/enforcement.json?search=recall_number:%22D-0830-2026%22",
    "raw_excerpt": "Carton label: Mycophenolate Mofetil for injection, USP, 500 mg/vial, Sterile, 4 Single Dose Vials, Rx only, Manufactured for: Mylan Institutional LLC, Morgantown, WV 26505, Made in India, NDC 67457-386-81.  Vial Label: Mycophenolate Mofetil for injection, USP, 500 mg/vial, Sterile, Single Dose Vial, Rx only, Manufactured for: Mylan Institutional LLC, Morgantown, WV 26505, Made in India, NDC 67457-386-00.\nFailed Dissolution Specifications\nLot: 3242616, Exp. April 2027; 8220216, Exp. Nov 2027",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  },
  "sunscreen": {
    "pk": "openfda#D-0826-2026",
    "source": "openfda",
    "notice_id": "D-0826-2026",
    "title": "drug recall: THE ONE SPF 50 INVISIBLE SUNSCREEN GEL, (Avobenzone 3%, Homosalate 7%, Octocrylene 10%, Octisalate 5",
    "product": "THE ONE SPF 50 INVISIBLE SUNSCREEN GEL, (Avobenzone 3%, Homosalate 7%, Octocrylene 10%, Octisalate 5%), 90ml - 3 fl. oz. Tube, Made in the U.S.A, Distributed by Allies Group Pte Ltd, Singapore 068914. UPC 8 885014 075853",
    "brand": "Allies Group Inc.",
    "batches": [
      "G23W03B"
    ],
    "model": null,
    "vehicles": [],
    "row_ref": null,
    "hazard_or_failed_test": "Subpotent Product: Firm Testing indicated the affected product may not reliably provide the SPF 50 protection stated on the label.",
    "remedy": null,
    "published_at": "2026-09-09",
    "first_seen_at": "2026-09-18T18:42:34Z",
    "url": "https://api.fda.gov/drug/enforcement.json?search=recall_number:%22D-0826-2026%22",
    "raw_excerpt": "THE ONE SPF 50 INVISIBLE SUNSCREEN GEL, (Avobenzone 3%, Homosalate 7%, Octocrylene 10%, Octisalate 5%), 90ml - 3 fl. oz. Tube, Made in the U.S.A, Distributed by Allies Group Pte Ltd, Singapore 068914. UPC 8 885014 075853\nSubpotent Product: Firm Testing indicated the affected product may not reliably provide the SPF 50 protection stated on the label.\nLots: G23W03B, Exp. 8/4/2027; A16X02, Exp. 1/20/2029: A16X03, Exp. 1/22/2029.",
    "mfg_date": null,
    "exp_date": null,
    "lab": null,
    "adapter": null
  }
} satisfies Record<string, Notice>;

/** Pinned group as mocked (rows 129, 42, 70). The spec says "first 3 rows in row order"; the component renders whatever it is given. */
export const pinnedAlert: PinnedAlert = {
  month: "JUL-2026",
  published_at: "2026-07-01",
  first_seen_at: "2026-09-18T18:40:42Z",
  count: 239,
  notices: [notices.aceclofenac, notices.paracetamolYuventis, notices.metformin],
};

/** Date groups as in feed-full-1536.png. `loaded` / `bySource` are the real counts in GET /v1/notices?limit=50. */
export const feedGroups: NoticeGroup[] = [
  { date: "2026-09-17", notices: [notices.sauna, notices.grill, notices.busyBoard, notices.mattress, notices.helmet], loaded: 14, bySource: { cpsc: 14 } },
  { date: "2026-09-10", notices: [notices.tiguan, notices.agaRange], loaded: 13, bySource: { cpsc: 12, nhtsa: 1 } },
  { date: "2026-09-09", notices: [notices.trokendi, notices.mycophenolate, notices.sunscreen], loaded: 23, bySource: { openfda: 23 } },
];

export const noFilters: FeedFilters = { source: null, since: null, q: "" };

/** The /mine demo household check: 15 things, 2 alerts (item ids as in the v2 fixtures). */
export const demoHousehold: HouseholdCheck = {
  name: "the demo household",
  as_of: "2026-09-20T09:38:00Z",
  medicines_checked: 4,
  matches: [
    {
      item: { item_id: "demo-alert", kind: "medicine", name: "Paracetamol Tablets IP 650mg", brand: "Forgo Pharmaceuticals", batch: "FT5427", purchase_date: "2026-07-12", case_id: "case_demo_ft5427", label: "Paracetamol" },
      notice: { pk: notices.paracetamolFt5427.pk, source: "cdsco_nsq", notice_id: notices.paracetamolFt5427.notice_id, row_ref: notices.paracetamolFt5427.row_ref },
    },
    {
      item: { item_id: "demo-vehicle", kind: "vehicle", name: "Jeep Compass", make: "Jeep", model: "Compass", year: 2022 },
      notice: { pk: notices.jeepCompass.pk, source: "nhtsa", notice_id: notices.jeepCompass.notice_id, row_ref: null },
    },
  ],
};

/** API console: "CPSC this week" after its first run (200 · 48 ms · 5 notices); body is the real response. */
export const cpscThisWeekBody = {
  "notices": [
    {
      "pdf_s3_key": null,
      "row_ref": null,
      "exp_date": null,
      "serial_ranges": [],
      "product": "Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits",
      "batches": [],
      "remedy": "Consumers should stop using the infrared and hybrid saunas immediately and contact Sauna360 to schedule a free in-home repair from a professional installer.; Repair",
      "url": "https://cpsc.gov/Recalls/2026/Sauna360-Recalls-Infrared-Saunas-Hybrid-Infrared-Saunas-and-Infrared-Kits-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-and-Burn-Hazards",
      "vehicles": [],
      "title": "Sauna360 Recalls Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits Due to Risk of Serious Injury or Death from Fire and Burn Hazards",
      "published_at": "2026-09-17",
      "source": "cpsc",
      "lab": null,
      "mfg_date": null,
      "hazard_or_failed_test": "The infrared panels in the saunas and kits can short circuit, causing them to overheat, posing a risk of serious injury from fire and burn hazards.",
      "brand_lc": "sauna360",
      "brand": "Sauna360 Inc.",
      "adapter": null,
      "model": null,
      "pk": "cpsc#10984",
      "first_seen_at": "2026-09-18T18:41:44Z",
      "notice_id": "10984",
      "raw_excerpt": "Sauna360 Recalls Infrared Saunas, Hybrid Infrared Saunas and Infrared Kits Due to Risk of Serious Injury or Death from Fire and Burn Hazards\nThis recall involves various infrared and hybrid sauna models and infrared (IR) kits. Customers who purchased custom rooms built with IR panels can check for the words \"Saunalogic,\" \"Infralogic,\" \"Carbonflex,\" or \"Tylö\" on their control panel or locate their product manual. Customers who purchased pre-configured infrared sauna rooms can identify their product by the brand badge on the front frame panel, the control panel, the manual or the logo handle. Consumers can also find the serial number located under the lower bench or on the wall under the upper bench depending on the unit and provide Sauna360 the serial number to determine if they have a recalled sauna. The IR sauna kits with panels, along with the following sauna model numbers, are included in this recall:\nInfrared Saunas, Hybrid Infrared Saunas and Infrared Kits",
      "source_confidence": null,
      "updated_at": "2026-09-19T18:24:35Z"
    },
    {
      "pdf_s3_key": null,
      "remedy": "Consumers should take the recalled toy away from children, stop using it immediately and contact Esjay for instructions on the repair. Consumers will be asked to unzip the page with red knobs, write “RECALLED” on both sides of the page and throw it away. Send a photo of the disposed page to Esjay US at esjay-service@outlook.com to receive a replacement page.; Repair",
      "row_ref": null,
      "pk": "cpsc#10982",
      "exp_date": null,
      "serial_ranges": [],
      "batches": [],
      "notice_id": "10982",
      "vehicles": [],
      "hazard_or_failed_test": "The recalled toy violates the small parts ban because the product is for children under three years of age and the red knobs can detach, posing a deadly choking hazard.",
      "published_at": "2026-09-17",
      "source": "cpsc",
      "lab": null,
      "mfg_date": null,
      "brand": "Shenzhen Yishijie Technology Co., Ltd., dba Esjay US",
      "url": "https://cpsc.gov/Recalls/2026/Esjay-US-Recalls-Toddler-Busy-Board-Montessori-Toys-Due-to-Risk-of-Serious-Injury-or-Death-from-Choking-Violates-Small-Parts-Ban",
      "product": "Esjay Toddler Busy Board Montessori Toys",
      "adapter": null,
      "model": null,
      "first_seen_at": "2026-09-18T18:41:44Z",
      "brand_lc": "shenzhen yishijie technology dba esjay us",
      "source_confidence": null,
      "title": "Esjay US Recalls Toddler Busy Board Montessori Toys Due to Risk of Serious Injury or Death from Choking; Violates Small Parts Ban",
      "updated_at": "2026-09-19T18:24:35Z",
      "raw_excerpt": "Esjay US Recalls Toddler Busy Board Montessori Toys Due to Risk of Serious Injury or Death from Choking; Violates Small Parts Ban\nThis recall involves Esjay Toddler Busy Board Montessori Toys. The busy boards are made of blue felt, have carrying handles, elastic cords and button closures. The front is printed with various cartoon dinosaurs, and the back is printed with 26 small squares, each corresponding to a letter of the alphabet. Each square contains the letter and a cartoon animal. The busy boards have five pages in total and the page with red knobs is the second page.\nEsjay Toddler Busy Board Montessori Toys"
    },
    {
      "pdf_s3_key": null,
      "raw_excerpt": "Char-Broil Recalls Bistro Pro Electric Grills Due to Risk of Electric Shock\nThis recall involves the Charbroil Bistro Pro Electric Grills with model descriptions Bistro Pro Electric Grill & Griddle + Charcoal, Bistro Electric Grill + Charcoal and Bistro Pro Tabletop Electric Grill. The grills were sold in full-size and tabletop configurations in Black (black and gray), Red, Blackout (all black) and Emerald (green). The units have a \"CB\" logo plate on the front of the lid and \"CHARBROIL\" printed on the front control panel. The product label listing the model and serial number, including a four-digit manufacturing date code in year and month (YYMM) format, is located on the bottom shelf of full-size grills and on the side bar of tabletop models. Only Bistro Pro Electric Grills with date codes of 2510 (Oct-2025), 2511 (Nov-2025) and 2512 (Dec-2025) are included in this recall.\nCharbroil Bistro Pro Electric Grills",
      "hazard_or_failed_test": "The grounding wire for the grill’s heating element can disconnect and lose fault protection, posing an electric shock hazard.",
      "row_ref": null,
      "brand_lc": "char-broil",
      "pk": "cpsc#10986",
      "exp_date": null,
      "serial_ranges": [],
      "notice_id": "10986",
      "title": "Char-Broil Recalls Bistro Pro Electric Grills Due to Risk of Electric Shock",
      "vehicles": [],
      "published_at": "2026-09-17",
      "source": "cpsc",
      "lab": null,
      "mfg_date": null,
      "batches": [
        "2510",
        "2511",
        "2512"
      ],
      "adapter": null,
      "remedy": "Consumers should stop using the recalled electric grills immediately and contact Char-Broil for a free repair kit. Consumers will be asked to register at www.charbroil.com/BistroProFix to receive repair instructions, a screwdriver, a wrench, screws and a label to affix to the grill after repair. Char-Broil is offering a digital $25 gift card, valid at participating retailers, to consumers who provide photo documentation of the completed repair.; Repair",
      "model": null,
      "first_seen_at": "2026-09-18T18:41:44Z",
      "url": "https://cpsc.gov/Recalls/2026/Char-Broil-Recalls-Bistro-Pro-Electric-Grills-Due-to-Risk-of-Electric-Shock",
      "source_confidence": null,
      "product": "Charbroil Bistro Pro Electric Grills",
      "brand": "Char-Broil LLC",
      "updated_at": "2026-09-19T18:24:35Z"
    },
    {
      "pdf_s3_key": null,
      "brand_lc": "toyworld168",
      "row_ref": null,
      "exp_date": null,
      "serial_ranges": [],
      "hazard_or_failed_test": "The squishy bun toys violate the mandatory safety standard for toys because the water beads inside the dumplings expand larger than permitted, posing a deadly ingestion hazard. If a water bead is ingested, it can pose ingestion, choking and intestinal obstruction hazards inside a child’s body, resulting in severe discomfort, vomiting, dehydration and a risk of death to a child.",
      "batches": [],
      "vehicles": [],
      "published_at": "2026-09-17",
      "product": "Rainbow Mystery Squishy Bun Toys",
      "source": "cpsc",
      "lab": null,
      "remedy": "Consumers should stop using the squishy dumpling toys immediately and contact Toyworld168 for a full refund. Consumers will be asked to write “RECALLED” in permanent marker on the squeezy dumpling and its tan plastic container, throw the toy away and email a photo of the disposed toy to toyworld16850@gmail.com.; Refund",
      "mfg_date": null,
      "url": "https://cpsc.gov/Recalls/2026/Toyworld168-Recalls-Rainbow-Mystery-Squishy-Bun-Toys-Due-to-Risk-of-Serious-Injury-or-Death-from-Water-Bead-Ingestion-Violate-Mandatory-Standard-for-Toys",
      "title": "Toyworld168 Recalls Rainbow Mystery Squishy Bun Toys Due to Risk of Serious Injury or Death from Water Bead Ingestion; Violate Mandatory Standard for Toys",
      "pk": "cpsc#10980",
      "adapter": null,
      "model": null,
      "first_seen_at": "2026-09-18T18:41:44Z",
      "notice_id": "10980",
      "source_confidence": null,
      "raw_excerpt": "Toyworld168 Recalls Rainbow Mystery Squishy Bun Toys Due to Risk of Serious Injury or Death from Water Bead Ingestion; Violate Mandatory Standard for Toys\nThis recall involves Rainbow Mystery Squishy Bun Toys. The squishy bun toys are a translucent green color, containing glitter and water beads. The toys have a cartoon face and are packaged in a tan plastic container shaped like a bamboo steamer. \"Rainbow MYSTERY\" and \"SUGAR EDITION\" are printed on the front of the removable package labeling. There are no markings on the product, other than the cartoon face.\nRainbow Mystery Squishy Bun Toys",
      "brand": "Toyworld168 Inc.",
      "updated_at": "2026-09-19T18:24:35Z"
    },
    {
      "url": "https://cpsc.gov/Recalls/2026/Regfear-Recalls-BedsPick-Mattresses-Due-to-Risk-of-Serious-Injury-or-Death-from-Fire-Violate-Mandatory-Flammability-Standard-for-Mattresses",
      "pdf_s3_key": null,
      "row_ref": null,
      "exp_date": null,
      "serial_ranges": [],
      "title": "Regfear Recalls BedsPick Mattresses Due to Risk of Serious Injury or Death from Fire; Violate Mandatory Flammability Standard for Mattresses",
      "batches": [],
      "raw_excerpt": "Regfear Recalls BedsPick Mattresses Due to Risk of Serious Injury or Death from Fire; Violate Mandatory Flammability Standard for Mattresses\nThis recall involves two styles of BedsPick branded Mattresses. The mattresses are 12 inches thick and sold in queen size. They have a white top and purple sides or a white top and gray sides and were sold compressed in a box. Prototype ID \"AMGSW066\" or \"AMGSW067\" and model numbers \"SME004\" or \"AMG005197_12_Q_GLT\" are printed on a sewn-in white label located on one side of the mattress.\nBedsPick Mattresses",
      "pk": "cpsc#10981",
      "model": "SME004",
      "vehicles": [],
      "published_at": "2026-09-17",
      "source": "cpsc",
      "lab": null,
      "mfg_date": null,
      "product": "BedsPick Mattresses",
      "notice_id": "10981",
      "adapter": null,
      "brand": "BedsPick Mattresses",
      "brand_lc": "bedspick mattresses",
      "first_seen_at": "2026-09-18T18:41:44Z",
      "source_confidence": null,
      "updated_at": "2026-09-19T18:24:35Z",
      "remedy": "Consumers should stop using the recalled mattresses immediately and contact Regfear for a full refund. Consumers will be asked to destroy the mattress, write in permanent marker “Recalled,” on the mattress’ top surface and email a photo of the destroyed mattress to BedsPickRecall@outlook.com. Consumers should then dispose of the recalled product. The refund will be issued after Regfear receives photos and written confirmation of disposal.; Refund",
      "hazard_or_failed_test": "The mattresses violate the mandatory flammability standard for mattresses, posing a risk of serious injury or death from fire."
    }
  ],
  "count": 5,
  "next_cursor": "eyJsaW1pdCI6NSwic2luY2UiOiIyMDI2LTA5LTE1Iiwic3JjIjp7ImNwc2MiOnsiZG9uZSI6ZmFsc2UsImVzayI6eyJwayI6ImNwc2MjMTA5ODEiLCJwdWJsaXNoZWRfYXQiOiIyMDI2LTA5LTE3Iiwic291cmNlIjoiY3BzYyJ9LCJza2lwIjowfX0sInYiOjF9",
  "source": "cpsc",
  "since": "2026-09-15",
  "q": null,
  "limit": 5
};

export const apiFixtureExamples = apiExamples(fixtureNow);
export const apiFixtureResult: TryItResult = {
  state: "done",
  response: { status: 200, ms: 48, body: cpscThisWeekBody, count: cpscThisWeekBody.count, next_cursor: cpscThisWeekBody.next_cursor },
};
export const API_BASE = "https://ilbmeuwrt7.execute-api.ap-south-1.amazonaws.com";
